# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='file_upload.FileUploaded/bytes/filename/mimetype')),
                ('resolved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
