# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='image_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='image_finder.ImageHeader'),
            preserve_default=False,
        ),
    ]
