# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_finder', '0002_imagedetail_image_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='imagedetail',
            name='image',
            field=models.FileField(upload_to='image_finder.FileUploaded/bytes/filename/mimetype'),
        ),
    ]
