# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_finder', '0004_auto_20160408_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='image',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
